//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebPortal.Localizations {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class TourismLoc {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal TourismLoc() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WebPortal.Localizations.TourismLoc", typeof(TourismLoc).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Shop Items of User (admin).
        /// </summary>
        public static string Index_Add_Shop_Items {
            get {
                return ResourceManager.GetString("Index_Add_Shop_Items", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add News about Future Article(admin).
        /// </summary>
        public static string Index_Add_Tour_Photo {
            get {
                return ResourceManager.GetString("Index_Add_Tour_Photo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Created Users(admin).
        /// </summary>
        public static string Index_Created_Users {
            get {
                return ResourceManager.GetString("Index_Created_Users", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home Page.
        /// </summary>
        public static string Index_Home {
            get {
                return ResourceManager.GetString("Index_Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Link Tours in Shop with Author(admin).
        /// </summary>
        public static string Index_Link_Tours_Author {
            get {
                return ResourceManager.GetString("Index_Link_Tours_Author", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        public static string Index_Login {
            get {
                return ResourceManager.GetString("Index_Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logout.
        /// </summary>
        public static string Index_Logout {
            get {
                return ResourceManager.GetString("Index_Logout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Main Page.
        /// </summary>
        public static string Index_Main_Page {
            get {
                return ResourceManager.GetString("Index_Main_Page", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registration.
        /// </summary>
        public static string Index_Registration {
            get {
                return ResourceManager.GetString("Index_Registration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shop.
        /// </summary>
        public static string Index_Shop {
            get {
                return ResourceManager.GetString("Index_Shop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update User Roles.
        /// </summary>
        public static string Index_Update_User_Role {
            get {
                return ResourceManager.GetString("Index_Update_User_Role", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter description.
        /// </summary>
        public static string Sho_PlaceHolder_Description {
            get {
                return ResourceManager.GetString("Sho_PlaceHolder_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter the price in field below.
        /// </summary>
        public static string Shop_Enter_Price {
            get {
                return ResourceManager.GetString("Shop_Enter_Price", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Admin Page for Shop.
        /// </summary>
        public static string Shop_Page_name {
            get {
                return ResourceManager.GetString("Shop_Page_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter tour name.
        /// </summary>
        public static string Shop_Placeholder_Tour_name {
            get {
                return ResourceManager.GetString("Shop_Placeholder_Tour_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter URL for tour image.
        /// </summary>
        public static string Shop_Placeholder_URL {
            get {
                return ResourceManager.GetString("Shop_Placeholder_URL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Author of the title will be.
        /// </summary>
        public static string Shop_Title_Autor_Name {
            get {
                return ResourceManager.GetString("Shop_Title_Autor_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select Author from available options bellow:.
        /// </summary>
        public static string Shop_Title_Autors {
            get {
                return ResourceManager.GetString("Shop_Title_Autors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add New Voting on Main Page.
        /// </summary>
        public static string Shop_Title_Page {
            get {
                return ResourceManager.GetString("Shop_Title_Page", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to URl.
        /// </summary>
        public static string Shop_url {
            get {
                return ResourceManager.GetString("Shop_url", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select Any Author.
        /// </summary>
        public static string Validation_Author_Required {
            get {
                return ResourceManager.GetString("Validation_Author_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description could be max 20 symbols.
        /// </summary>
        public static string Validation_description_max_symbol {
            get {
                return ResourceManager.GetString("Validation_description_max_symbol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Tour Name is required.
        /// </summary>
        public static string Validation_Name_Required {
            get {
                return ResourceManager.GetString("Validation_Name_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Price could be between 1 and 50.
        /// </summary>
        public static string Validation_Price {
            get {
                return ResourceManager.GetString("Validation_Price", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The price field is required.
        /// </summary>
        public static string Validation_Price_Required {
            get {
                return ResourceManager.GetString("Validation_Price_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is not uniq name.
        /// </summary>
        public static string Validation_Uniq_Name {
            get {
                return ResourceManager.GetString("Validation_Uniq_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Url of Image Tour is required.
        /// </summary>
        public static string Validation_Url_Required {
            get {
                return ResourceManager.GetString("Validation_Url_Required", resourceCulture);
            }
        }
    }
}
